In [2]:
import numpy as np

In [5]:
a = np.random.randn(9, 6) + 1j*np.random.randn(9, 6)
a

array([[ 0.18679211-0.58613817j,  0.66105806+0.72940831j,
         1.94155926+2.11537285j,  0.15561265+0.69651338j,
        -0.19558983+0.30197164j,  1.14444803-0.50165836j],
       [-0.23120622+0.42746604j, -0.91392947-0.59307338j,
        -0.61642407-0.1941232j , -0.59437196-0.2544132j ,
        -1.54163437-1.45656316j,  1.98163775+0.80689423j],
       [-0.47553272-0.18876597j, -0.60267548-0.8839262j ,
        -0.34134062+0.05220696j, -0.06889767+0.20087192j,
         0.58375441+0.02582946j, -0.50532479-0.44745928j],
       [ 0.47280562-0.35793636j, -0.68987605+0.10710111j,
         0.61636711-1.18350814j, -0.45534469-0.85755756j,
        -1.11748874+0.72909313j, -0.2322787 -0.23447804j],
       [-2.13578914-0.27042392j,  0.28804422+1.49861651j,
        -0.23524185+0.29303103j, -0.4520227 -0.444152j  ,
         0.59930071-0.69904778j, -1.30114021-0.36963842j],
       [ 1.95775578+1.88624935j, -0.19819555-0.36230829j,
        -0.36523163-0.87368313j, -0.30566183-1.59366093j,
        -

In [6]:
b = np.random.randn(2, 7, 8, 3) + 1j*np.random.randn(2, 7, 8, 3)
b

array([[[[ 9.03465210e-01-2.09774324e+00j,
           1.52635342e+00+4.50433399e-01j,
          -1.92444474e+00+9.46268803e-01j],
         [ 3.73832165e-01+5.27183663e-01j,
           1.00018311e+00+1.83532890e+00j,
          -4.51526563e-01+5.55774655e-01j],
         [ 3.01961711e-01+1.27667828e+00j,
          -5.10003537e-01+5.61714255e-01j,
           3.38632195e-01-6.94918584e-01j],
         [ 1.55363955e-01-4.23629248e-01j,
           5.42897727e-01+7.58787841e-01j,
          -7.96257780e-01+1.16380332e+00j],
         [ 7.74979781e-01+4.04223982e-02j,
          -3.58497495e-01-1.04887429e-01j,
           4.84213411e-01+4.80173104e-01j],
         [ 8.03793434e-02+5.58462227e-02j,
          -6.75871556e-01-1.65541237e+00j,
          -6.29455778e-01-7.82381438e-01j],
         [ 2.29377164e+00+1.72432032e+00j,
          -7.20418199e-01-3.71014957e-01j,
          -5.75910177e-01-4.05095813e-01j],
         [ 1.54714767e+00-5.59043890e-01j,
           2.79156195e-02-1.17181674e+00j,
    

In [7]:
u, s, vh = np.linalg.svd(a, full_matrices=True)

In [8]:
u.shape, s.shape, vh.shape

((9, 9), (6,), (6, 6))

In [9]:
np.allclose(a, np.dot(u[:, :6] * s, vh))

True

In [13]:
smat = np.zeros((9, 6), dtype=complex)
smat[:6, :6] = np.diag(s)
smat

array([[6.20509483+0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j,
        0.        +0.j, 0.        +0.j],
       [0.        +0.j, 4.61846384+0.j, 0.        +0.j, 0.        +0.j,
        0.        +0.j, 0.        +0.j],
       [0.        +0.j, 0.        +0.j, 3.75259796+0.j, 0.        +0.j,
        0.        +0.j, 0.        +0.j],
       [0.        +0.j, 0.        +0.j, 0.        +0.j, 2.91344776+0.j,
        0.        +0.j, 0.        +0.j],
       [0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j,
        2.17321636+0.j, 0.        +0.j],
       [0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j,
        0.        +0.j, 1.23758942+0.j],
       [0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j,
        0.        +0.j, 0.        +0.j],
       [0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j,
        0.        +0.j, 0.        +0.j],
       [0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j,
        0.        +0.j, 

In [14]:
np.allclose(a, np.dot(u, np.dot(smat, vh)))

True