# 使用pickle序列化numpy array

In [1]:
import pickle
import numpy as np

In [4]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
f = open('x.pkl','wb') 

In [18]:
pickle.dump(x,f)

In [19]:
f.close()

In [20]:
!ls

Array的inputan和output.ipynb   数组与矩阵运算.ipynb
x.pkl                          数组的创建与访问.ipynb


In [21]:
f = open('x.pkl','rb')

In [22]:
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
f.close()

In [24]:
np.save('one_array',x)

In [25]:
!ls

Array的inputan和output.ipynb   数组与矩阵运算.ipynb
one_array.npy                  数组的创建与访问.ipynb
x.pkl


In [26]:
np.load('one_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
y = np.arange(20)

In [28]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
np.savez('two_array.npz',a=x,b=y)

In [31]:
!ls

Array的inputan和output.ipynb   x.pkl
one_array.npy                  数组与矩阵运算.ipynb
two_array.npz                  数组的创建与访问.ipynb


In [32]:
c = np.load('two_array.npz')

In [34]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])