# 快速创建数组

In [1]:
import numpy as np

In [2]:
np.random.randn(10)

array([-0.62775604,  2.26609977, -1.47737525, -0.2517986 , -0.58812107,
        1.13482444,  1.30923235, -0.02937578, -0.42841282, -0.42434171])

In [7]:
np.random.randint(10, size=20).reshape((5,4)).T

array([[6, 0, 6, 2, 1],
       [9, 6, 6, 7, 6],
       [2, 0, 0, 8, 4],
       [7, 0, 9, 9, 8]])

# 数组的运算

In [8]:
a = np.random.randint(10, size=20).reshape((4,5))
b = np.random.randint(10, size=20).reshape((4,5))

In [10]:
a

array([[9, 2, 2, 4, 1],
       [2, 7, 8, 5, 0],
       [3, 5, 2, 7, 9],
       [6, 8, 1, 9, 0]])

In [11]:
b

array([[0, 1, 6, 7, 2],
       [5, 9, 1, 3, 9],
       [2, 8, 8, 4, 9],
       [4, 1, 9, 2, 8]])

In [12]:
a+b

array([[ 9,  3,  8, 11,  3],
       [ 7, 16,  9,  8,  9],
       [ 5, 13, 10, 11, 18],
       [10,  9, 10, 11,  8]])

In [14]:
a-b

array([[ 9,  1, -4, -3, -1],
       [-3, -2,  7,  2, -9],
       [ 1, -3, -6,  3,  0],
       [ 2,  7, -8,  7, -8]])

In [15]:
a*b

array([[ 0,  2, 12, 28,  2],
       [10, 63,  8, 15,  0],
       [ 6, 40, 16, 28, 81],
       [24,  8,  9, 18,  0]])

In [16]:
a/b

/Users/she/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[       inf, 2.        , 0.33333333, 0.57142857, 0.5       ],
       [0.4       , 0.77777778, 8.        , 1.66666667, 0.        ],
       [1.5       , 0.625     , 0.25      , 1.75      , 1.        ],
       [1.5       , 8.        , 0.11111111, 4.5       , 0.        ]])

# 矩阵的创建

In [17]:
np.mat([[1,2,3],[4,5,6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [18]:
a

array([[9, 2, 2, 4, 1],
       [2, 7, 8, 5, 0],
       [3, 5, 2, 7, 9],
       [6, 8, 1, 9, 0]])

In [19]:
np.mat(a)

matrix([[9, 2, 2, 4, 1],
        [2, 7, 8, 5, 0],
        [3, 5, 2, 7, 9],
        [6, 8, 1, 9, 0]])

# 矩阵的运算

In [25]:
A = np.mat(a)
B = np.mat(b)

In [26]:
A+B

matrix([[ 9,  3,  8, 11,  3],
        [ 7, 16,  9,  8,  9],
        [ 5, 13, 10, 11, 18],
        [10,  9, 10, 11,  8]])

In [31]:
a+b

array([[ 9,  3,  8, 11,  3],
       [ 7, 16,  9,  8,  9],
       [ 5, 13, 10, 11, 18],
       [10,  9, 10, 11,  8]])

In [32]:
a+B

matrix([[ 9,  3,  8, 11,  3],
        [ 7, 16,  9,  8,  9],
        [ 5, 13, 10, 11, 18],
        [10,  9, 10, 11,  8]])

In [34]:
A-B

matrix([[ 9,  1, -4, -3, -1],
        [-3, -2,  7,  2, -9],
        [ 1, -3, -6,  3,  0],
        [ 2,  7, -8,  7, -8]])

In [36]:
A*B.T

matrix([[ 44,  86,  75,  72],
        [ 90,  96, 144,  97],
        [ 84, 164, 171, 121],
        [ 77, 130, 120,  59]])

# Array常用函数

In [40]:
a = np.random.randint(10, size=20).reshape((4,5))
a

[[8 3 6 3 1]
 [2 2 8 0 4]
 [0 2 2 5 3]
 [4 8 0 7 9]]


In [41]:
np.unique(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
sum(a);a.sum()

77

In [45]:
a.sum()

77

In [48]:
sum(a[0])

21

In [49]:
a.max()

9

In [50]:
max(a[2])

5